version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:17.7.2

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint:check
      - run: npm run build
      - run:
          name: Run test
          command: npm run test
          no_output_timeout: 2m
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  deploy-alpha:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish --tag alpha

  deploy-release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish to npm
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  version: 2
  npm-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy-alpha:
          context: reachfive
          requires:
            - test
          filters:
            tags:
              only: /^v.*-alpha\.[0-9]/
            branches:
              ignore: /.*/
      - deploy-release:
          context: reachfive
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
